services:
  mysql:
    image: mysql:8.3
    container_name: radar-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: radar
      MYSQL_USER: radar_user
      MYSQL_PASSWORD: radar_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: radar-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: radar-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto.data:/mosquitto/data
      - ./mosquitto.log:/mosquitto/log
    command: sh -c "touch /mosquitto/data/pwfile.conf && chmod 0600 /mosquitto/data/pwfile.conf && mosquitto_passwd -b /mosquitto/data/pwfile.conf havicare hitCare && mosquitto -c /mosquitto/config/mosquitto.conf"

  simulator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radar-simulator
    restart: unless-stopped
    environment:
      MQTT_SERVER: 88.99.104.197
      MQTT_PORT: 1883
      MQTT_USERNAME: havicare
      MQTT_PASSWORD: hitCare

volumes:
  mysql_data:
